spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-auth-server
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8085

security:
  jwt:
    auth:
      converter:
        resource-id: spring-boot-client
        principal-attribute: preferred_username
